root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main github.com/benc-uk/terrain-gen/generate/cli"
delay = 200
exclude_dir = ["junk", "tmp", "vendor"]

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
